nome = str(input('Digite seu nome completo: ')).strip()
up = ' '.join(nome.upper().split())
low = ' '.join(nome.lower().split())
total = len(''.join(nome.split()))
div = nome.split()
print(f'Tudo em maiúsculo é: {up}')
print(f'Tudo em minúsculo é: {low}')
print(f'Total de letras: {total}')
print(f'Letras no primeiro nome: {len(div[0])}')