nome = str(input('Digite seu nome completo: '))
up = nome.upper()
low = nome.lower()
total = len(''.join(nome.split()))
div = nome.split()
print(f'Tudo em maiúsculo é: {up}')
print(f'Tudo em minúsculo é: {low}')
print(f'Total de letras: {total}')
print(f'Letras no primeiro nome: {len(div[0])}')