frase = input('Digite uma frase: ').upper().strip()
qtd = frase.count('A')
prim = frase.find('A')
ult = frase.rfind('A')
print(f'{qtd} letras a encontradas.')
print(f'Apereceu primeiro na posição {prim + 1}')
print(f'E foi visto pela ultima vez na posição {ult + 1}')
